#!/bin/bash

# reset shell colors
tput init

# https://stackoverflow.com/questions/59895/how-to-get-the-source-directory-of-a-bash-script-from-within-the-script-itself
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  PROJECT_ROOT="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$PROJECT_ROOT/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
PROJECT_ROOT="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

# required imports
source "${PROJECT_ROOT}"/variables/manifest.sh
source "${PROJECT_ROOT}"/utils/manifest.sh
source "${PROJECT_ROOT}"/lib/manifest.sh

# Gerar senha aleatória para o usuário deployzdg
deploy_password=$(openssl rand -base64 16 | tr -dc 'A-Za-z0-9')

# interactive CLI
inquiry_options

# inicia barra de progresso (34 etapas da instalação completa)
init_progress 34

# system config
system_create_user

# dependencies related
system_update
system_set_timezone
system_node_install
system_pm2_install
system_docker_install
system_puppeteer_dependencies
system_libs
system_snapd_install
system_nginx_install
system_certbot_install

# backend related
system_unzip_zpro
system_set_user_mod
backend_set_env
backend_db_create
backend_chrome_install
backend_node_dependencies
system_docker_restart
backend_db_migrate
backend_db_seed
backend_start_pm2
backend_bd_update
backend_nginx_setup
# docker_list_and_kill_redis
# create_redis_service
# check_redis_status

# frontend related
frontend_set_env
frontend_node_dependencies
frontend_node_build
frontend_start_pm2
frontend_nginx_setup

# network related
system_nginx_conf
system_nginx_restart
system_certbot_setup
system_docker_restart
system_delete_zip
install_firewall
system_success
